#############################################################################
# Makefile for building: ProjetLOA
# Generated by qmake (2.01a) (Qt 4.7.3) on: Tue Mar 26 14:13:49 2013
# Project:  ProjetLOA.pro
# Template: app
# Command: /usr/X11R7/bin/qmake -o Makefile ProjetLOA.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/X11R7/mkspecs/linux-g++ -I. -I/usr/X11R7/include/QtCore -I/usr/X11R7/include/QtGui -I/usr/X11R7/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/X11R7/lib
LIBS          = $(SUBLIBS)  -L/usr/X11R7/lib -lQtGui -L/usr/X11R7/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/X11R7/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		vue/mainwindow.cpp \
		modele/contacts.cpp \
		modele/contact.cpp \
		vue/listecontacts.cpp \
		vue/affichercontact.cpp \
		vue/editercontact.cpp \
		modele/champ.cpp \
		modele/texte.cpp \
		modele/modelelistecontacts.cpp \
		modele/modeleaffichercontact.cpp \
		controleur/controleur.cpp \
		modele/structure.cpp \
		modele/url.cpp \
		modele/card.cpp \
		modele/loc.cpp \
		modele/timestamp.cpp \
		modele/enum.cpp \
		vue/locedit.cpp \
		vue/enumedit.cpp \
		modele/modeleafficherstructure.cpp \
		vue/structureedit.cpp \
		vue/ajouterchamp.cpp moc_mainwindow.cpp \
		moc_contacts.cpp \
		moc_controleur.cpp \
		moc_listecontacts.cpp \
		moc_affichercontact.cpp \
		moc_editercontact.cpp \
		moc_modelelistecontacts.cpp \
		moc_modeleaffichercontact.cpp \
		moc_locedit.cpp \
		moc_enumedit.cpp \
		moc_modeleafficherstructure.cpp \
		moc_structureedit.cpp \
		moc_ajouterchamp.cpp
OBJECTS       = main.o \
		mainwindow.o \
		contacts.o \
		contact.o \
		listecontacts.o \
		affichercontact.o \
		editercontact.o \
		champ.o \
		texte.o \
		modelelistecontacts.o \
		modeleaffichercontact.o \
		controleur.o \
		structure.o \
		url.o \
		card.o \
		loc.o \
		timestamp.o \
		enum.o \
		locedit.o \
		enumedit.o \
		modeleafficherstructure.o \
		structureedit.o \
		ajouterchamp.o \
		moc_mainwindow.o \
		moc_contacts.o \
		moc_controleur.o \
		moc_listecontacts.o \
		moc_affichercontact.o \
		moc_editercontact.o \
		moc_modelelistecontacts.o \
		moc_modeleaffichercontact.o \
		moc_locedit.o \
		moc_enumedit.o \
		moc_modeleafficherstructure.o \
		moc_structureedit.o \
		moc_ajouterchamp.o
DIST          = /usr/X11R7/mkspecs/common/g++.conf \
		/usr/X11R7/mkspecs/common/unix.conf \
		/usr/X11R7/mkspecs/common/linux.conf \
		/usr/X11R7/mkspecs/qconfig.pri \
		/usr/X11R7/mkspecs/modules/qt_webkit_version.pri \
		/usr/X11R7/mkspecs/features/qt_functions.prf \
		/usr/X11R7/mkspecs/features/qt_config.prf \
		/usr/X11R7/mkspecs/features/exclusive_builds.prf \
		/usr/X11R7/mkspecs/features/default_pre.prf \
		/usr/X11R7/mkspecs/features/release.prf \
		/usr/X11R7/mkspecs/features/default_post.prf \
		/usr/X11R7/mkspecs/features/warn_on.prf \
		/usr/X11R7/mkspecs/features/qt.prf \
		/usr/X11R7/mkspecs/features/unix/thread.prf \
		/usr/X11R7/mkspecs/features/moc.prf \
		/usr/X11R7/mkspecs/features/resources.prf \
		/usr/X11R7/mkspecs/features/uic.prf \
		/usr/X11R7/mkspecs/features/yacc.prf \
		/usr/X11R7/mkspecs/features/lex.prf \
		/usr/X11R7/mkspecs/features/include_source_dir.prf \
		ProjetLOA.pro
QMAKE_TARGET  = ProjetLOA
DESTDIR       = 
TARGET        = ProjetLOA

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_listecontacts.h ui_affichercontact.h ui_editercontact.h ui_locedit.h ui_structureedit.h ui_ajouterchamp.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProjetLOA.pro  /usr/X11R7/mkspecs/linux-g++/qmake.conf /usr/X11R7/mkspecs/common/g++.conf \
		/usr/X11R7/mkspecs/common/unix.conf \
		/usr/X11R7/mkspecs/common/linux.conf \
		/usr/X11R7/mkspecs/qconfig.pri \
		/usr/X11R7/mkspecs/modules/qt_webkit_version.pri \
		/usr/X11R7/mkspecs/features/qt_functions.prf \
		/usr/X11R7/mkspecs/features/qt_config.prf \
		/usr/X11R7/mkspecs/features/exclusive_builds.prf \
		/usr/X11R7/mkspecs/features/default_pre.prf \
		/usr/X11R7/mkspecs/features/release.prf \
		/usr/X11R7/mkspecs/features/default_post.prf \
		/usr/X11R7/mkspecs/features/warn_on.prf \
		/usr/X11R7/mkspecs/features/qt.prf \
		/usr/X11R7/mkspecs/features/unix/thread.prf \
		/usr/X11R7/mkspecs/features/moc.prf \
		/usr/X11R7/mkspecs/features/resources.prf \
		/usr/X11R7/mkspecs/features/uic.prf \
		/usr/X11R7/mkspecs/features/yacc.prf \
		/usr/X11R7/mkspecs/features/lex.prf \
		/usr/X11R7/mkspecs/features/include_source_dir.prf \
		/usr/X11R7/lib/libQtGui.prl \
		/usr/X11R7/lib/libQtCore.prl
	$(QMAKE) -o Makefile ProjetLOA.pro
/usr/X11R7/mkspecs/common/g++.conf:
/usr/X11R7/mkspecs/common/unix.conf:
/usr/X11R7/mkspecs/common/linux.conf:
/usr/X11R7/mkspecs/qconfig.pri:
/usr/X11R7/mkspecs/modules/qt_webkit_version.pri:
/usr/X11R7/mkspecs/features/qt_functions.prf:
/usr/X11R7/mkspecs/features/qt_config.prf:
/usr/X11R7/mkspecs/features/exclusive_builds.prf:
/usr/X11R7/mkspecs/features/default_pre.prf:
/usr/X11R7/mkspecs/features/release.prf:
/usr/X11R7/mkspecs/features/default_post.prf:
/usr/X11R7/mkspecs/features/warn_on.prf:
/usr/X11R7/mkspecs/features/qt.prf:
/usr/X11R7/mkspecs/features/unix/thread.prf:
/usr/X11R7/mkspecs/features/moc.prf:
/usr/X11R7/mkspecs/features/resources.prf:
/usr/X11R7/mkspecs/features/uic.prf:
/usr/X11R7/mkspecs/features/yacc.prf:
/usr/X11R7/mkspecs/features/lex.prf:
/usr/X11R7/mkspecs/features/include_source_dir.prf:
/usr/X11R7/lib/libQtGui.prl:
/usr/X11R7/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile ProjetLOA.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ProjetLOA1.0.0 || $(MKDIR) .tmp/ProjetLOA1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ProjetLOA1.0.0/ && $(COPY_FILE) --parents vue/mainwindow.h modele/contacts.h modele/contact.h controleur/controleur.h vue/listecontacts.h vue/affichercontact.h vue/editercontact.h modele/champ.h modele/texte.h modele/modelelistecontacts.h modele/modeleaffichercontact.h controleur/controleur.h modele/structure.h modele/url.h modele/card.h modele/loc.h modele/timestamp.h modele/enum.h vue/locedit.h vue/enumedit.h modele/modeleafficherstructure.h vue/structureedit.h vue/ajouterchamp.h .tmp/ProjetLOA1.0.0/ && $(COPY_FILE) --parents main.cpp vue/mainwindow.cpp modele/contacts.cpp modele/contact.cpp vue/listecontacts.cpp vue/affichercontact.cpp vue/editercontact.cpp modele/champ.cpp modele/texte.cpp modele/modelelistecontacts.cpp modele/modeleaffichercontact.cpp controleur/controleur.cpp modele/structure.cpp modele/url.cpp modele/card.cpp modele/loc.cpp modele/timestamp.cpp modele/enum.cpp vue/locedit.cpp vue/enumedit.cpp modele/modeleafficherstructure.cpp vue/structureedit.cpp vue/ajouterchamp.cpp .tmp/ProjetLOA1.0.0/ && $(COPY_FILE) --parents vue/mainwindow.ui vue/listecontacts.ui vue/affichercontact.ui vue/editercontact.ui vue/locedit.ui vue/structureedit.ui vue/ajouterchamp.ui .tmp/ProjetLOA1.0.0/ && (cd `dirname .tmp/ProjetLOA1.0.0` && $(TAR) ProjetLOA1.0.0.tar ProjetLOA1.0.0 && $(COMPRESS) ProjetLOA1.0.0.tar) && $(MOVE) `dirname .tmp/ProjetLOA1.0.0`/ProjetLOA1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ProjetLOA1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_contacts.cpp moc_controleur.cpp moc_listecontacts.cpp moc_affichercontact.cpp moc_editercontact.cpp moc_modelelistecontacts.cpp moc_modeleaffichercontact.cpp moc_controleur.cpp moc_locedit.cpp moc_enumedit.cpp moc_modeleafficherstructure.cpp moc_structureedit.cpp moc_ajouterchamp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_contacts.cpp moc_controleur.cpp moc_listecontacts.cpp moc_affichercontact.cpp moc_editercontact.cpp moc_modelelistecontacts.cpp moc_modeleaffichercontact.cpp moc_controleur.cpp moc_locedit.cpp moc_enumedit.cpp moc_modeleafficherstructure.cpp moc_structureedit.cpp moc_ajouterchamp.cpp
moc_mainwindow.cpp: vue/mainwindow.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/mainwindow.h -o moc_mainwindow.cpp

moc_contacts.cpp: modele/contact.h \
		modele/champ.h \
		modele/contacts.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) modele/contacts.h -o moc_contacts.cpp

moc_controleur.cpp: vue/mainwindow.h \
		modele/contacts.h \
		modele/contact.h \
		modele/champ.h \
		controleur/controleur.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) controleur/controleur.h -o moc_controleur.cpp

moc_listecontacts.cpp: vue/listecontacts.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/listecontacts.h -o moc_listecontacts.cpp

moc_affichercontact.cpp: vue/affichercontact.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/affichercontact.h -o moc_affichercontact.cpp

moc_editercontact.cpp: vue/editercontact.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/editercontact.h -o moc_editercontact.cpp

moc_modelelistecontacts.cpp: modele/contacts.h \
		modele/contact.h \
		modele/champ.h \
		modele/modelelistecontacts.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) modele/modelelistecontacts.h -o moc_modelelistecontacts.cpp

moc_modeleaffichercontact.cpp: modele/contact.h \
		modele/champ.h \
		modele/modeleaffichercontact.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) modele/modeleaffichercontact.h -o moc_modeleaffichercontact.cpp

moc_controleur.cpp: vue/mainwindow.h \
		modele/contacts.h \
		modele/contact.h \
		modele/champ.h \
		controleur/controleur.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) controleur/controleur.h -o moc_controleur.cpp

moc_locedit.cpp: modele/loc.h \
		modele/champ.h \
		vue/locedit.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/locedit.h -o moc_locedit.cpp

moc_enumedit.cpp: modele/enum.h \
		modele/champ.h \
		vue/enumedit.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/enumedit.h -o moc_enumedit.cpp

moc_modeleafficherstructure.cpp: modele/structure.h \
		modele/champ.h \
		modele/modeleafficherstructure.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) modele/modeleafficherstructure.h -o moc_modeleafficherstructure.cpp

moc_structureedit.cpp: modele/structure.h \
		modele/champ.h \
		vue/structureedit.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/structureedit.h -o moc_structureedit.cpp

moc_ajouterchamp.cpp: vue/ajouterchamp.h
	/usr/X11R7/bin/moc $(DEFINES) $(INCPATH) vue/ajouterchamp.h -o moc_ajouterchamp.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_listecontacts.h ui_affichercontact.h ui_editercontact.h ui_locedit.h ui_structureedit.h ui_ajouterchamp.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_listecontacts.h ui_affichercontact.h ui_editercontact.h ui_locedit.h ui_structureedit.h ui_ajouterchamp.h
ui_mainwindow.h: vue/mainwindow.ui \
		vue/editercontact.h \
		vue/affichercontact.h \
		vue/listecontacts.h
	/usr/X11R7/bin/uic vue/mainwindow.ui -o ui_mainwindow.h

ui_listecontacts.h: vue/listecontacts.ui
	/usr/X11R7/bin/uic vue/listecontacts.ui -o ui_listecontacts.h

ui_affichercontact.h: vue/affichercontact.ui
	/usr/X11R7/bin/uic vue/affichercontact.ui -o ui_affichercontact.h

ui_editercontact.h: vue/editercontact.ui
	/usr/X11R7/bin/uic vue/editercontact.ui -o ui_editercontact.h

ui_locedit.h: vue/locedit.ui
	/usr/X11R7/bin/uic vue/locedit.ui -o ui_locedit.h

ui_structureedit.h: vue/structureedit.ui
	/usr/X11R7/bin/uic vue/structureedit.ui -o ui_structureedit.h

ui_ajouterchamp.h: vue/ajouterchamp.ui
	/usr/X11R7/bin/uic vue/ajouterchamp.ui -o ui_ajouterchamp.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp controleur/controleur.h \
		vue/mainwindow.h \
		modele/contacts.h \
		modele/contact.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: vue/mainwindow.cpp vue/mainwindow.h \
		ui_mainwindow.h \
		vue/locedit.h \
		modele/loc.h \
		modele/champ.h \
		vue/enumedit.h \
		modele/enum.h \
		vue/structureedit.h \
		modele/structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o vue/mainwindow.cpp

contacts.o: modele/contacts.cpp modele/contacts.h \
		modele/contact.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contacts.o modele/contacts.cpp

contact.o: modele/contact.cpp modele/contact.h \
		modele/champ.h \
		modele/card.h \
		modele/enum.h \
		modele/loc.h \
		modele/structure.h \
		modele/texte.h \
		modele/timestamp.h \
		modele/url.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o modele/contact.cpp

listecontacts.o: vue/listecontacts.cpp vue/listecontacts.h \
		ui_listecontacts.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listecontacts.o vue/listecontacts.cpp

affichercontact.o: vue/affichercontact.cpp vue/affichercontact.h \
		ui_affichercontact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o affichercontact.o vue/affichercontact.cpp

editercontact.o: vue/editercontact.cpp vue/editercontact.h \
		ui_editercontact.h \
		vue/ajouterchamp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editercontact.o vue/editercontact.cpp

champ.o: modele/champ.cpp modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o champ.o modele/champ.cpp

texte.o: modele/texte.cpp modele/texte.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o texte.o modele/texte.cpp

modelelistecontacts.o: modele/modelelistecontacts.cpp modele/modelelistecontacts.h \
		modele/contacts.h \
		modele/contact.h \
		modele/champ.h \
		modele/structure.h \
		modele/texte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelelistecontacts.o modele/modelelistecontacts.cpp

modeleaffichercontact.o: modele/modeleaffichercontact.cpp modele/modeleaffichercontact.h \
		modele/contact.h \
		modele/champ.h \
		vue/ajouterchamp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modeleaffichercontact.o modele/modeleaffichercontact.cpp

controleur.o: controleur/controleur.cpp controleur/controleur.h \
		vue/mainwindow.h \
		modele/contacts.h \
		modele/contact.h \
		modele/champ.h \
		modele/modeleaffichercontact.h \
		modele/modelelistecontacts.h \
		modele/texte.h \
		modele/structure.h \
		modele/url.h \
		modele/card.h \
		modele/loc.h \
		modele/timestamp.h \
		modele/enum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controleur.o controleur/controleur.cpp

structure.o: modele/structure.cpp modele/structure.h \
		modele/champ.h \
		modele/texte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o structure.o modele/structure.cpp

url.o: modele/url.cpp modele/url.h \
		modele/texte.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o url.o modele/url.cpp

card.o: modele/card.cpp modele/card.h \
		modele/champ.h \
		modele/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o modele/card.cpp

loc.o: modele/loc.cpp modele/loc.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loc.o modele/loc.cpp

timestamp.o: modele/timestamp.cpp modele/timestamp.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timestamp.o modele/timestamp.cpp

enum.o: modele/enum.cpp modele/enum.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enum.o modele/enum.cpp

locedit.o: vue/locedit.cpp vue/locedit.h \
		modele/loc.h \
		modele/champ.h \
		ui_locedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o locedit.o vue/locedit.cpp

enumedit.o: vue/enumedit.cpp vue/enumedit.h \
		modele/enum.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enumedit.o vue/enumedit.cpp

modeleafficherstructure.o: modele/modeleafficherstructure.cpp modele/modeleafficherstructure.h \
		modele/structure.h \
		modele/champ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modeleafficherstructure.o modele/modeleafficherstructure.cpp

structureedit.o: vue/structureedit.cpp vue/structureedit.h \
		modele/structure.h \
		modele/champ.h \
		ui_structureedit.h \
		modele/modeleafficherstructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o structureedit.o vue/structureedit.cpp

ajouterchamp.o: vue/ajouterchamp.cpp vue/ajouterchamp.h \
		ui_ajouterchamp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ajouterchamp.o vue/ajouterchamp.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_contacts.o: moc_contacts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_contacts.o moc_contacts.cpp

moc_controleur.o: moc_controleur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controleur.o moc_controleur.cpp

moc_listecontacts.o: moc_listecontacts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listecontacts.o moc_listecontacts.cpp

moc_affichercontact.o: moc_affichercontact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_affichercontact.o moc_affichercontact.cpp

moc_editercontact.o: moc_editercontact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editercontact.o moc_editercontact.cpp

moc_modelelistecontacts.o: moc_modelelistecontacts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modelelistecontacts.o moc_modelelistecontacts.cpp

moc_modeleaffichercontact.o: moc_modeleaffichercontact.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modeleaffichercontact.o moc_modeleaffichercontact.cpp

moc_locedit.o: moc_locedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_locedit.o moc_locedit.cpp

moc_enumedit.o: moc_enumedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enumedit.o moc_enumedit.cpp

moc_modeleafficherstructure.o: moc_modeleafficherstructure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modeleafficherstructure.o moc_modeleafficherstructure.cpp

moc_structureedit.o: moc_structureedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_structureedit.o moc_structureedit.cpp

moc_ajouterchamp.o: moc_ajouterchamp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ajouterchamp.o moc_ajouterchamp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

